### PR TITLE
Updates for auth2

### PR DESCRIPTION
**Pull request by msneddon**
Updates required to switch to Auth2.  Despite @cshenry making it a fun challenge to get tests to work for me :) I at least managed to get one handcrafted test to run successfully in CI for building a metabolic model, so updated token passing/validation through to the workspace seems to work properly now with Auth2.

### CODE REVIEW

**Comment by cshenry** [comment]
Please be patient on this guys. This is a pretty huge PR. For one, I'm not at all certain you've found all the places in the code where the old Workspace path appears.

Second, in the deploy.cfg file, the "scratch" entry appears twice.. which could of course, cause problems.

Third, all clients switched from "asynch" to "service" version... which is concerning... Are we abandoning "asynch" mode, or was this a mistake?

Fourth, you have a python auth client now... I'm not sure how the perl code is making use of this... Is it just there because the type compiler makes it?

**Comment by scanon** [comment]
I think the diffs are misleading.  Most of these are autogenerated clients.

We should remove the second scratch.  I've seen that cause issues in the past.

For local method calls, the sync method is probably the correct one.

I think the python auth client can be ignored.  It is just generated when you compile the spec file to generate the clients.

**Comment by cshenry** [comment]
Well, if you look carefully, the Workspace lib has changed. That's a fairly big change given how prevalent and central that library is.

I'm not sure I understand your comment on the client libs. Shane - you're saying the "sync" method is right? You mean, the dynamic service? Because as is, it seems like the code is using the dynamic service clients... and it seems like that won't work because I'm calling those methods with a call-back URL treating them like asynchronous calls. OF course, what I don't know is if we somehow made the change at some point to no longer use different clients for asynchronous calls...

**Comment by msneddon** [comment]
This PR illustrates why unit tests that can be run by anyone and have reasonable coverage are so important and worth the effort- they give everyone on the project the freedom to make large changes quickly with confidence.  Right now, because of how the few tests that do exist are hardcoded, you're the only one that can really verify that nothing was broken, and unfortunately you probably have to that by hand right now.

I was able to hack up the tests and configs and my own workspace to test creating an FBA model (which does have to talk to the WS with the new auth credentials to get/save data, call KBaseReport through the callback server) and that worked.  But of course I can't be sure anything else isn't broken.

To address your other comments, the Workspace client update is required.  I did a search to find everywhere that looked like the client was being initialized, but of course I may have missed one if the call isn't required for the build fba model function.

The update to the other SDK module clients aren't strictly required, but it is safer to update them (and it also fixes some bugs like the context object not properly being passed through).  The default clients created for these modules are still asynchronous, but that's hidden from you (at least I don't think they are explicitly marked as async).  So these changes should be safe, and like I mentioned worked properly at least with KBaseReport.

We can probably remove the generated Python auth code, but if anyone copies the new python clients from your module directly, they won't work without these.  Your perl code doesn't use these.

Finally, the scratch configuration is duplicated because you have multiple configuration blocks, one for [fba_tools], one for [ModelSEED] and one for [UtilConfig].  If you don't need the config in one place or the other, feel free to remove (I think in github now you can push commits to my fork on that branch) or tell me what you want.  I just put the same configs where ever you were already duplicating the url configs.

**Comment by cshenry** [comment]
I see this was merged, which is fine. But note, this is NOT the master repo for this service. That is still cshenry/fba_tools. That's the URL for the production deploy of fba_tools. I'll pull the changes into that repo and test.

**Pull request merged**
